# Generated by Django 4.2b1 on 2023-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
